"""Graph Hint helpers for protected natural sets.

Graph Hints are deliberately sparse. They are not a taxonomy and they do not
replace Leiden communities; they only protect high-confidence natural sets
from being split apart when the global match threshold is otherwise healthy.
"""

import re

GRAPH_HINT_RE = re.compile(r"^- \*\*Graph Hint:\*\*\s*(.*)$", re.M)
GRAPH_CONTEXT_RE = re.compile(r"## Graph Context\n", re.M)
ROLE_LINE_RE = re.compile(r"^- \*\*Role:\*\*", re.M)

PROTECTED_HINTS = {
    "Shapes",
    "Animal",
    "BodyPart",
    "Clothing",
    "Color",
    "Country",
    "Direction",
    "FamilyMember",
    "Language",
    "Month",
    "Number",
    "Profession",
    "SchoolSupply",
    "Season",
    "TransportMode",
    "Weather",
    "Weekday",
}

GRAPH_HINT_WORDS = {
    "Shapes": {
        "Achteck",
        "Dreieck",
        "Fünfeck",
        "Halbkreis",
        "Herz",
        "Kegel",
        "Kreis",
        "Kugel",
        "Linie",
        "Oval",
        "Pfeil",
        "Punkt",
        "Pyramide",
        "Quadrat",
        "Raute",
        "Rechteck",
        "Sechseck",
        "Stern",
        "Würfel",
        "Zylinder",
    },

    "Country": {
        "Afghanistan",
        "Argentinien",
        "Belgien",
        "Brasilien",
        "China",
        "Dänemark",
        "Deutschland",
        "England",
        "Finnland",
        "Frankreich",
        "Griechenland",
        "Indien",
        "Irland",
        "Italien",
        "Japan",
        "Kanada",
        "Mexiko",
        "Niederlande",
        "Norwegen",
        "Polen",
        "Portugal",
        "Russland",
        "Schweden",
        "Schweiz",
        "Spanien",
        "Südkorea",
        "Türkei",
        "USA",
        "Ukraine",
        "Vereinigtes Königreich",
        "Österreich",
    },
    "Language": {
        "Arabisch",
        "Chinesisch",
        "Deutsch",
        "Englisch",
        "Französisch",
        "Griechisch",
        "Italienisch",
        "Japanisch",
        "Portugiesisch",
        "Russisch",
        "Spanisch",
        "Türkisch",
    },
    "Weekday": {
        "Montag",
        "Dienstag",
        "Mittwoch",
        "Donnerstag",
        "Freitag",
        "Samstag",
        "Sonnabend",
        "Sonntag",
    },
    "Month": {
        "Januar",
        "Februar",
        "März",
        "April",
        "Mai",
        "Juni",
        "Juli",
        "August",
        "September",
        "Oktober",
        "November",
        "Dezember",
    },
    "Season": {
        "Frühling",
        "Sommer",
        "Herbst",
        "Winter",
    },
    "Number": {
        "null",
        "eins",
        "zwei",
        "drei",
        "vier",
        "fünf",
        "sechs",
        "sieben",
        "acht",
        "neun",
        "zehn",
        "elf",
        "zwölf",
        "dreizehn",
        "vierzehn",
        "fünfzehn",
        "sechzehn",
        "siebzehn",
        "achtzehn",
        "neunzehn",
        "zwanzig",
        "dreißig",
        "vierzig",
        "fünfzig",
        "sechzig",
        "siebzig",
        "achtzig",
        "neunzig",
        "hundert",
        "tausend",
        "erste",
        "zweite",
        "dritte",
        "vierte",
        "fünfte",
        "sechste",
        "siebte",
        "achte",
        "neunte",
        "zehnte",
    },
    "Color": {
        "beige",
        "blau",
        "braun",
        "bunt",
        "gelb",
        "grau",
        "grün",
        "lila",
        "orange",
        "rosa",
        "rot",
        "schwarz",
        "violett",
        "weiß",
    },
    "Direction": {
        "außen",
        "dort",
        "drinnen",
        "draußen",
        "heraus",
        "hier",
        "hinaus",
        "hinein",
        "hinten",
        "links",
        "neben",
        "oberhalb",
        "rechts",
        "unten",
        "vorne",
        "zwischen",
    },
    "BodyPart": {
        "Arm",
        "Auge",
        "Bauch",
        "Bein",
        "Brust",
        "Daumen",
        "Ellbogen",
        "Finger",
        "Fingernagel",
        "Fuß",
        "Gesicht",
        "Hals",
        "Hand",
        "Knochen",
        "Kopf",
        "Körper",
        "Mund",
        "Muskel",
        "Nagel",
        "Nase",
        "Nerv",
        "Ohr",
        "Rücken",
        "Schulter",
        "Zahn",
        "Zunge",
    },
    "FamilyMember": {
        "Angehörige",
        "Bruder",
        "Cousin",
        "Cousine",
        "Ehefrau",
        "Ehemann",
        "Eltern",
        "Familie",
        "Geschwister",
        "Großeltern",
        "Großmutter",
        "Großvater",
        "Kind",
        "Mutter",
        "Onkel",
        "Schwester",
        "Sohn",
        "Tante",
        "Tochter",
        "Vater",
    },
    "SchoolSupply": {
        "Anspitzer",
        "Bleistift",
        "Block",
        "Bogen",
        "Buch",
        "Büroklammer",
        "Füller",
        "Geodreieck",
        "Heft",
        "Heftklammer",
        "Klebeband",
        "Klebstoff",
        "Kugelschreiber",
        "Kuli",
        "Lineal",
        "Locher",
        "Mappe",
        "Marker",
        "Notizbuch",
        "Ordner",
        "Papier",
        "Patrone",
        "Radiergummi",
        "Schere",
        "Schnellhefter",
        "Schreibwaren",
        "Spitzer",
        "Tacker",
        "Tafel",
        "Textmarker",
        "Tintenpatrone",
        "Umschlag",
        "Unterlage",
        "Zirkel",
    },
    "TransportMode": {
        "Auto",
        "Bahn",
        "Bus",
        "Fahrrad",
        "Fahrzeug",
        "Flugzeug",
        "Motorrad",
        "Straßenbahn",
        "Taxi",
        "Verkehrsmittel",
        "Zug",
    },
    "Animal": {
        "Falter",
        "Hase",
        "Haustier",
        "Hummel",
        "Hund",
        "Insekt",
        "Katze",
        "Kuh",
        "Nachtfalter",
        "Pferd",
        "Rind",
        "Tier",
        "Vieh",
        "Vogel",
        "Wiesel",
        "Wildbiene",
    },
    "Profession": {
        "Anwalt",
        "Apotheker",
        "Architekt",
        "Arzt",
        "Bauer",
        "Beamter",
        "Busfahrer",
        "Bäcker",
        "Chef",
        "Designer",
        "Elektriker",
        "Fahrer",
        "Feuerwehrmann",
        "Fotograf",
        "Friseur",
        "Gärtner",
        "Handwerker",
        "Informatiker",
        "Ingenieur",
        "Journalist",
        "Kellner",
        "Koch",
        "Krankenpfleger",
        "Landwirt",
        "Lehrer",
        "Lehrkraft",
        "Lehrling",
        "Maler",
        "Manager",
        "Mechaniker",
        "Metzger",
        "Musiker",
        "Pilot",
        "Polizist",
        "Programmierer",
        "Richter",
        "Schauspieler",
        "Schreiner",
        "Schriftsteller",
        "Sekretär",
        "Sänger",
        "Tanzlehrer",
        "Taxifahrer",
        "Tierarzt",
        "Tischler",
        "Übersetzer",
        "Verkäufer",
        "Wissenschaftler",
    },
    "Clothing": {
        "Anzug",
        "Hemd",
        "Hose",
        "Jacke",
        "Kleid",
        "Kleidung",
        "Kostüm",
        "Mantel",
        "Schuh",
        "Stiefel",
    },
    "Weather": {
        "Feuchtigkeit",
        "Gewitter",
        "Hitze",
        "Kälte",
        "Klima",
        "Regen",
        "regnen",
        "Schnee",
        "Sonne",
        "Sturm",
        "Temperatur",
        "Unwetter",
        "Wetter",
        "Wind",
        "Wolke",
    },
}


def infer_graph_hint(word, content=""):
    """Return a high-confidence graph hint for a word, or None.

    Keep this conservative. A wrong hint is worse than no hint because protected
    hints can override community splitting.
    """
    for hint in sorted(PROTECTED_HINTS):
        if word in GRAPH_HINT_WORDS.get(hint, set()):
            return hint
    return None


def extract_graph_hint(content):
    match = GRAPH_HINT_RE.search(content)
    if not match:
        return None
    value = match.group(1).strip()
    return value if value and value.lower() != "none" else None


def ensure_graph_hint_line(content, hint):
    """Insert or update the Graph Hint line inside Graph Context."""
    if not hint:
        return content
    if GRAPH_HINT_RE.search(content):
        return GRAPH_HINT_RE.sub(f"- **Graph Hint:** {hint}", content, count=1)

    role = ROLE_LINE_RE.search(content)
    if role:
        return content[:role.start()] + f"- **Graph Hint:** {hint}\n" + content[role.start():]

    graph_context = GRAPH_CONTEXT_RE.search(content)
    if graph_context:
        insert_at = graph_context.end()
        return content[:insert_at] + f"- **Graph Hint:** {hint}\n" + content[insert_at:]

    return content
